# About the numpy ramdom package

## Numpy is a numerical package for python.
#### NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

In [2]:
import numpy as np

In [3]:
np.random.uniform(0.0, 10.0)

0.7154939914839731

### Array Creation
####  you can create an array from a regular Python list or tuple using the array function

In [5]:
a = np.array([2,3,4])

In [6]:
a

array([2, 3, 4])

In [7]:
a.dtype

dtype('int32')

In [8]:
 b = np.array([1.2, 3.5, 5.1])

In [9]:
b.dtype

dtype('float64')

##### Arrays transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [10]:
b = np.array([(1.5,2,3), (4,5,6)])

In [11]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### 2d Array

In [3]:
a = np.arange(15).reshape(3, 5)


In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])